# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Enable auto-download of JDK toolchains
org.gradle.java.installations.auto-download=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=0.2.1+26.1.2
maven_group=com.github.yukkuritaku.modernwarpmenu
archives_base_name=modernwarpmenu

# Dependencies
fabric_version=0.150.0+26.1.2
architectury_version=19.0.1
yacl_version=3.9.3+26.1-fabric
modmenu_version=18.0.0-beta.1
rei_version=21.11.814
skyblocker_version=v6.5.0+26.1.2
conditional_mixin_version=0.6.4
hypixel_mod_api_version=1.0.1
hm_api_version=1.0.3+26.1
