# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=0.2.4+26.2
maven_group=com.github.yukkuritaku.modernwarpmenu
archives_base_name=modernwarpmenu

# Dependencies
fabric_version=0.154.0+26.2
architectury_version=21.0.2
yacl_version=3.9.5+26.2-fabric
modmenu_version=20.0.0-beta.4
rei_version=26.2.820
skyblocker_version=v6.6.0+26.2
conditional_mixin_version=0.6.4
hypixel_mod_api_version=1.0.2+build.1+mc26.1
hm_api_version=1.0.4+26.2
itemlist_version=0.0.14+26.2